name: {{SERVICE_NAME}} service ci
on:
  push:
    branches: [ "main" ]
    paths:
      - "{{SERVICE_NAME}}/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/{{SERVICE_NAME}}-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "{{SERVICE_NAME}}/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/{{SERVICE_NAME}}-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean install -DskipTests -f {{SERVICE_NAME}}
      - name: Run Maven Test
        run: mvn test -f {{SERVICE_NAME}}
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./{{SERVICE_NAME}}
          push: false